homeassistant:
  # Name of the location where Home Assistant is running
  name: Pasteur
  country: FR
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret elevation
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Paris
  # Customization file
  customize: !include customize.yaml
  #whitelist_external_dirs:
  #  - /data/homeassistant
  #  - /home/homeassistant/maps
  auth_providers:
    - type: homeassistant
    #- type: trusted_networks
    #  trusted_networks:
    #    - 192.168.12.0/24
  auth_mfa_modules:
    - type: totp

websocket_api:

http:
  server_port: 8123
  ssl_certificate: /home/homeassistant/certs/fullchain.pem
  ssl_key: /home/homeassistant/certs/privkey.pem
  cors_allowed_origins:
    - https://hass.home.fossar.net:8213
    - https://hass.home.fossar.net

# See https://www.home-assistant.io/integrations/emulated_roku/
# Used to control hass from Logitech Harmony remote
emulated_roku:
  servers:
    - name: Home Assistant
      listen_port: 8060

# Database configuration
recorder:
  commit_interval: 30

lovelace:
  mode: yaml
  resources:
    - url: /local/template-entity-row/template-entity-row.js
      type: module
    - url: /local/auto-entities/auto-entities.js
      type: module
    - url: /local/custom-header.js
      type: module
    - url: /local/lovelace-cards/tiles-card/tiles-card.js
      type: js
    - url: /local/mini-graph-card-bundle.js
      type: module
    - url: /local/community/lovelace-meteofrance-weather-card/meteofrance-weather-card.js
      type: module

default_config:

frontend:
  themes: !include_dir_merge_named themes/

# Text to speech
tts:
  - platform: google_translate

logger:
  default: info

sun:

prometheus:
  namespace: hass
  filter:
    include_domains:
      - sensor
      - light
      - switch

emulated_hue:
  host_ip: 192.168.12.35
  listen_port: 80
  expose_by_default: false
  exposed_domains:
    - light
    - group
    - switch
  entities:
    light.basement_escalier_switch:
      name: "escalier sous-sol"
      hidden: false
    light.bedroom_bathroom_dimmer:
      name: "chambre douche"
      hidden: false
    light.bedroom_left_dimmer:
      name: "chambre lampe"
      hidden: false
    light.blue_light_desk:
      name: "blue lampe"
      hidden: false
    light.entree_switch:
      name: "entree"
      hidden: false
    light.dressing_switch:
      name: "dressing"
      hidden: false
    light.escalier_switch:
      name: "escalier"
      hidden: false
    light.poutre_dimmer:
      name: "poutre"
      hidden: false
    light.kitchen_switch:
      name: "cuisine"
      hidden: false
    light.living_ball_switch:
      name: "living ball"
      hidden: false
    light.piano_switch:
      name: "piano"
      hidden: false
    light.table_dimmer:
      name: "table"
      hidden: false
    light.wled_blue:
      name: "led blue"
      hidden: false
    light.wled_poutre:
      name: "led poutre"
      hidden: false
    light.terrace_switch:
      name: "terrasse"
      hidden: false
    light.bedroom_switch:
      name: "appliques de la chambre"
      hidden: false
    group.hall_lights:
      name: "hall"
      hidden: false
    group.blue_lights:
      name: "blue"
      hidden: false
    group.upstairs_lights:
      name: "etage"
      hidden: false
    group.bedroom:
      name: "chambre"
      hidden: false

script: !include_dir_merge_named scripts/
light: !include_dir_merge_list lights/
sensor: !include_dir_merge_list sensors/
automation: !include automations.yaml
automation mine: !include_dir_merge_list automations/
scene: !include_dir_merge_list scenes/
group: !include groups.yaml
switch: !include_dir_merge_list switches/
climate: !include_dir_merge_list climates/
input_boolean: !include_dir_merge_named input_booleans/
