homeassistant:
  # Name of the location where Home Assistant is running
  name: Pasteur
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret elevation
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Paris
  # Customization file
  customize: !include customize.yaml
  #whitelist_external_dirs:
  #  - /data/homeassistant
  #  - /home/homeassistant/maps
  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks:
        - 192.168.12.0/24
  auth_mfa_modules:
    - type: totp

websocket_api:



#http:
#  server_port: 8123
#  ssl_certificate: /home/homeassistant/certs/fullchain.pem
#  ssl_key: /home/homeassistant/certs/privkey.pem
#  base_url: !secret http_baseurl
http:
  server_port: 8123
  ssl_certificate: /home/homeassistant/certs/fullchain.pem
  ssl_key: /home/homeassistant/certs/privkey.pem
  cors_allowed_origins:
    - https://hass.home.fossar.net:8213
    - https://hass.home.fossar.net

remote:
  - platform: harmony
    name: HarmonyHub
    host: 192.168.12.20

# See https://www.home-assistant.io/integrations/emulated_roku/
# Used to control hass from Logitech Harmony remote
emulated_roku:
  servers:
    - name: Home Assistant
      listen_port: 8060

# Monitor brother printer
brother:

# Database configuration
recorder:
  commit_interval: 30

lovelace:
  mode: yaml
  resources:
    - url: /local/auto-entities/auto-entities.js
      type: module
    - url: /local/custom-header.js
      type: module
    - url: /local/lovelace-cards/tiles-card/tiles-card.js
      type: js
    - url: /local/mini-graph-card-bundle.js
      type: module
    - url: /local/custom_ui/dark-sky-weather-card.js
      type: module

default_config:

frontend:
  themes: !include_dir_merge_named themes/

# Text to speech
tts:
  - platform: google_translate

logger:
  default: info

sun:

google:
  client_id: !secret google_api_clientid
  client_secret: !secret google_api_clientsecret
  track_new_calendar: false

script: !include_dir_merge_named scripts/
light: !include_dir_merge_list lights/
sensor: !include_dir_merge_list sensors/
automation: !include automations.yaml
automation mine: !include_dir_merge_list automations/
scene: !include_dir_merge_list scenes/
group: !include groups.yaml
mqtt: !include mqtt.yaml
switch: !include_dir_merge_list switches/
climate: !include_dir_merge_list climates/
input_boolean: !include_dir_merge_named input_booleans/
