homeassistant:
  # Name of the location where Home Assistant is running
  name: Pasteur
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret elevation
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Paris
  # Customization file
  customize: !include customize.yaml
  #whitelist_external_dirs:
  #  - /data/homeassistant
  #  - /home/homeassistant/maps
  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks:
        - 192.168.12.0/24

http:
  server_port: 8123
  ssl_certificate: /home/homeassistant/certs/fullchain.pem
  ssl_key: /home/homeassistant/certs/privkey.pem
  base_url: !secret http_baseurl

lovelace:
  mode: yaml

default_config:

frontend:
  themes: !include_dir_merge_named themes/

# Text to speech
tts:
  - platform: google_translate

logger:
  default: info

sun:

google:
  client_id: !secret google_api_clientid
  client_secret: !secret google_api_clientsecret
  track_new_calendar: false

script: !include_dir_merge_named scripts/
sensor: !include_dir_merge_list sensors/
automation: !include automations.yaml
automation mine: !include_dir_merge_list automations/
scene: !include scenes.yaml
scene mine: !include_dir_merge_list scenes/
group: !include groups.yaml
mqtt: !include mqtt.yaml
switch: !include_dir_merge_list switches/
climate: !include_dir_merge_list climates/
