homeassistant:
  # Name of the location where Home Assistant is running
  name: Pasteur
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret elevation
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Paris
  # Customization file
  customize: !include customize.yaml
  #whitelist_external_dirs:
  #  - /data/homeassistant
  #  - /home/homeassistant/maps

default_config:

# Text to speech
tts:
  - platform: google_translate

logger:
  default: info

script: !include_dir_named scripts/
automation: !include automations.yaml
automation mine: !include_dir_list automations/
scene: !include scenes.yaml
scene mine: !include_dir_list scenes/
group: !include groups.yaml

mqtt: !include mqtt.yaml
