title: Home
custom_header:
  compact_mode: true
  header_text: '{{ date }} - {{ time }}'
  footer_mode: false
  hide_help: false
views:
  - title: Lights
    type: custom:grid-layout
    layout:
      grid-template-columns: auto
      grid-template-rows: auto
      grid-template-areas: |
        "one"
        "footer"
    path: lights
    icon: 'mdi:lightbulb'
    badges: []
    cards:
      - type: vertical-stack
        view_layout:
          grid-area: one
        cards:
          - type: horizontal-stack
            columns: 2
            cards:
              - type: light
                entity: light.poutre_dimmer
                name: Poutre
                icon: 'mdi:lightbulb'
              - type: light
                entity: light.table_dimmer
                name: Table
                icon: 'mdi:lightbulb'
          - type: 'custom:auto-entities'
            card:
              type: entities
              show_header_toggle: true
              title: Upstairs
            filter:
              include:
                - domain: light
                  group: group.living_lights
                  entity_id: "light.*_switch"
                  options:
                    type: custom:template-entity-row
                    name: >
                      {{ config.entity | regex_replace(find='^light\.', replace='') | regex_replace(find='_switch$', replace='') | regex_replace(find='_', replace=' ') | title }}
                    toggle: true
                    active: "{{ is_state(config.entity, 'on') }}"
                - domain: light
                  group: group.living_lights
                  entity_id: "light.wled_*"
                  options:
                    type: custom:template-entity-row
                    name: >
                      {{ config.entity | regex_replace(find='^light\.', replace='') | regex_replace(find='_switch$', replace='') | regex_replace(find='_', replace=' ') | title }}
                    toggle: true
                    active: "{{ is_state(config.entity, 'on') }}"
                - domain: light
                  group: group.kitchen_lights
                  entity_id: "light.*_switch"
                  options:
                    type: custom:template-entity-row
                    name: >
                      {{ config.entity | regex_replace(find='^light\.', replace='') | regex_replace(find='_switch$', replace='') | regex_replace(find='_', replace=' ') | title }}
                    toggle: true
                    active: "{{ is_state(config.entity, 'on') }}"
                - domain: light
                  group: group.terrace_lights
                  entity_id: "light.*_switch"
                  options:
                    type: custom:template-entity-row
                    name: >
                      {{ config.entity | regex_replace(find='^light\.', replace='') | regex_replace(find='_switch$', replace='') | regex_replace(find='_', replace=' ') | title }}
                    toggle: true
                    active: "{{ is_state(config.entity, 'on') }}"
            sort:
              method: name
          - type: horizontal-stack
            column: 2
            cards:
              - type: light
                entity: light.bedroom_left_dimmer
                name: Bed left
                icon: 'mdi:lightbulb'
              - type: light
                entity: light.bedroom_bathroom_dimmer
                name: Shower room
                icon: 'mdi:lightbulb'
      - type: 'custom:auto-entities'
        card:
          type: entities
          show_header_toggle: true
          title: Bedroom
        filter:
          include:
            - domain: light
              group: group.bedroom_lights
              entity_id: "light.*_switch"
              options:
                type: custom:template-entity-row
                name: >
                  {{ config.entity | regex_replace(find='^light\.', replace='') | regex_replace(find='_switch$', replace='') | regex_replace(find='_dimmer$', replace='') | regex_replace(find='_', replace=' ') | title }}
                toggle: true
                active: "{{ is_state(config.entity, 'on') }}"
        sort:
          method: name
      - type: 'custom:auto-entities'
        card:
          type: entities
          show_header_toggle: true
          title: Hall
        filter:
          include:
            - domain: light
              group: group.hall_lights
              entity_id: "light.*_switch"
              options:
                type: custom:template-entity-row
                name: >
                  {{ config.entity | regex_replace(find='^light\.', replace='') | regex_replace(find='_switch$', replace='') | regex_replace(find='_', replace=' ') | title }}
                toggle: true
                active: "{{ is_state(config.entity, 'on') }}"
        sort:
          method: name
      - type: 'custom:auto-entities'
        card:
          type: entities
          show_header_toggle: true
          title: Basement
        filter:
          include:
            - domain: light
              group: group.basement_lights
              entity_id: "light.*_switch"
              options:
                type: custom:template-entity-row
                name: >
                  {{ config.entity | regex_replace(find='^light\.', replace='') | regex_replace(find='_switch$', replace='') | regex_replace(find='_', replace=' ') | title }}
                toggle: true
                active: "{{ is_state(config.entity, 'on') }}"
        sort:
          method: name
      - type: 'custom:auto-entities'
        card:
          type: entities
          show_header_toggle: true
          title: Blue
        filter:
          include:
            - domain: light
              group: group.blue_lights
              entity_id: "light.*"
        sort:
          method: name
      - type: 'custom:auto-entities'
        view_layout:
          grid-area: footer
        card:
          type: entities
          title: Random
          show_header_toggle: false
        filter:
          include:
            - entity_id: "input_boolean.random_lights"
  - title: Weather
    type: custom:grid-layout
    layout:
      grid-template-columns: auto
      grid-template-rows: auto
      grid-template-areas: |
        "main"
    path: weather
    icon: 'mdi:weather-partly-cloudy'
    badges: []
    cards:
      - type: "custom:meteofrance-weather-card"
        view_layout:
          grid-area: main
        name: Saint-Ouen
        entity: weather.saint_ouen
        cloudCoverEntity: sensor.saint_ouen_cloud_cover
        rainChanceEntity: sensor.saint_ouen_rain_chance
        freezeChanceEntity: sensor.saint_ouen_freeze_chance
        snowChanceEntity: sensor.saint_ouen_snow_chance
        uvEntity: sensor.saint_ouen_uv
        rainForecastEntity: sensor.saint_ouen_next_rain
        alertEntity: sensor.44_weather_alert
        number_of_forecasts: "5"
        current: true
        details: true
        one_hour_forecast: true
        alert_forecast: true
        forecast: true
  - title: Confort
    type: custom:grid-layout
    layout:
      grid-template-columns: auto
      grid-template-rows: auto
      grid-template-areas: |
        "one two three"
        "four five six"
        "footer footer footer"
      mediaquery:
        "(max-width: 600px)":
          grid-template-columns: 50% 50%
          grid-template-areas: |
            "one two"
            "three four"
            "five six"
            "footer footer"
    path: confort
    icon: 'mdi:radiator'
    badges: []
    cards:
      - type: thermostat
        entity: climate.bedroom
        name: Bedroom
        view_layout:
          grid-area: one
      - type: thermostat
        entity: climate.blue
        name: Blue
        view_layout:
          grid-area: two
      - type: thermostat
        entity: climate.pink
        name: Pink
        view_layout:
          grid-area: three
      - type: thermostat
        entity: climate.living
        name: Living
        view_layout:
          grid-area: four
      - type: thermostat
        entity: climate.kitchen
        name: Kitchen
        view_layout:
          grid-area: five
      - type: thermostat
        entity: climate.hall
        name: Hall
        view_layout:
          grid-area: six
      - type: 'custom:auto-entities'
        view_layout:
          grid-area: footer
        card:
          type: entities
          title: Overrides
          show_header_toggle: false
        filter:
          include:
            - entity_id: "input_boolean.override_heater_*"
  - title: Temperature
    type: custom:grid-layout
    layout:
      grid-template-columns: auto
      grid-template-rows: auto
      grid-template-areas: |
        "one two"
        "footer footer"
      mediaquery:
        "(max-width: 600px)":
          grid-template-columns: 100%
          grid-template-areas: |
            "one"
            "two"
            "footer"
    path: temperature
    icon: 'mdi:thermometer'
    badges: []
    cards:
      - type: 'custom:auto-entities'
        view_layout:
          grid-area: one
        card:
          type: entities
          title: Temperature
          show_header_toggle: false
        filter:
          include:
            - entity_id: "sensor.*_temperature"
        sort:
          method: name
      - type: 'custom:auto-entities'
        view_layout:
          grid-area: two
        card:
          type: entities
          title: Humidity
          show_header_toggle: false
        filter:
          include:
            - entity_id: "sensor.*_humidity"
        sort:
          method: name
      - type: 'custom:auto-entities'
        view_layout:
          grid-area: footer
        card:
          type: entities
          title: Estrade dehumidifier
          show_header_toggle: false
        filter:
          include:
            - entity_id: "input_boolean.override_estrade_dehum"
  - title: Battery
    path: Battery
    icon: 'mdi:battery-70'
    badges: []
    cards:
      - type: 'custom:auto-entities'
        card:
          type: entities
          show_header_toggle: false
          title: Zigbee sensors
        filter:
          include:
            - entity_id: "sensor.*_battery"
          attributes:
            manufacturer: "Xiaomi"
            model: "Aqara*"
        sort:
          method: state
          reverse: false
          numeric: true
  - title: Debug
    path: Debug
    icon: 'mdi:account-hard-hat'
    badges: []
    cards:
      - type: vertical-stack
        cards:
          - type: entity
            entity: switch.yokis_hub
            name: Yokis Hub
            icon: 'mdi:router-wireless'
          - type: entity
            entity: switch.estrade_relay
            name: Estrade Dehumidifier
            icon: 'mdi:water'
          - type: entity
            entity: switch.estrade_dehum_status
            name: Estrade Dehumidifier Status LED
            icon: 'mdi:alarm-light'
