- platform: template
  lights:
    blue_desk_switch:
      friendly_name: "Blue Light Desk"
      level_template: >
        {% if is_state('switch.blue_light_desk','on') %}255{% else %}0{% endif %}
      value_template: >
        {{ is_state('switch.blue_light_desk','on') }}
      icon_template: mdi:lightbulb
      turn_on:
        service: switch.turn_on
        entity_id: switch.blue_light_desk
      turn_off:
        service: switch.turn_off
        entity_id: switch.blue_light_desk
