- platform: template
  lights:
    living_ball_switch:
      friendly_name: "Living ball"
      level_template: >
        {% if is_state('switch.living_ball','on') %}255{% else %}0{% endif %}
      value_template: >
        {{ is_state('switch.living_ball','on') }}
      icon_template: >
        {% if is_state('switch.living_ball', 'off') %}
          mdi:lightbulb
        {% else %}
          mdi:lightbulb-on
        {% endif %}
      turn_on:
        service: switch.turn_on
        entity_id: switch.living_ball
      turn_off:
        service: switch.turn_off
        entity_id: switch.living_ball
      #set_level:
      #  service_template: >
      #    {% if brightness > 0 %}switch.turn_on{% else %}switch.turn_off{% endif %}
      #  data:
      #    entity_id: switch.living_ball
