- platform: darksky
  name: darksky
  api_key: !secret darksky_apikey
  language: fr
  forecast:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
  scan_interval:
    minutes: 10
  units: auto
  monitored_conditions:
    - alerts
    - apparent_temperature
    - apparent_temperature_high
    - apparent_temperature_low
    - cloud_cover
    - daily_summary
    - humidity
    - icon
    - moon_phase
    - nearest_storm_bearing
    - nearest_storm_distance
    - ozone
    - precip_accumulation
    - precip_intensity
    - precip_intensity_max
    - precip_probability
    - precip_type
    - pressure
    - summary
    - sunrise_time
    - sunset_time
    - temperature
    - temperature_high
    - temperature_low
    - uv_index
    - visibility
    - wind_bearing
    - wind_gust
    - wind_speed
