# Thermostat for bedroom heater
- platform: generic_thermostat
  name: bedroom
  heater: switch.heater_bedroom
  target_sensor: sensor.0x00158d00045b289c_temperature
  min_temp: 15
  max_temp: 22
  precision: 0.1
  ac_mode: false
  target_temp: 18
  away_temp: 16
  min_cycle_duration:
    minutes: 2
  initial_hvac_mode: "heat"
  cold_tolerance: 0.3
  hot_tolerance: 0.1
