# Thermostat for bedroom heater
- platform: generic_thermostat
  name: bedroom
  heater: switch.bedroom_heater
  target_sensor: sensor.z03mmc_bedroom_hum_temp_temperature
  min_temp: 15
  max_temp: 23
  precision: 0.1
  ac_mode: false
  away_temp: 16
  min_cycle_duration:
    seconds: 10
  initial_hvac_mode: "off"
  cold_tolerance: 0.1
  hot_tolerance: 0.1
