# Thermostat for pink heater
- platform: generic_thermostat
  name: pink
  heater: switch.pink_heater
  target_sensor: sensor.atc_pink_temp
  min_temp: 15
  max_temp: 23
  precision: 0.1
  ac_mode: false
  away_temp: 16
  min_cycle_duration:
    seconds: 10
  initial_hvac_mode: "off"
  cold_tolerance: 0.5
  hot_tolerance: 0.1
