# Thermostat for pink heater
- platform: generic_thermostat
  name: pink
  heater: switch.pink_heater
  target_sensor: sensor.pink_hum_temp_temperature
  min_temp: 15
  max_temp: 27
  precision: 0.1
  ac_mode: false
  target_temp: 18
  away_temp: 16
  min_cycle_duration:
    seconds: 10
  initial_hvac_mode: "heat"
  cold_tolerance: 0.1
  hot_tolerance: 0.1
