- alias: Turn ON basement escalier light on vibration
  initial_state: true
  trigger:
    platform: state
    entity_id: sensor.basement_vibr_escalier_action
    to: 'vibration'
  condition:
    - condition: state
      entity_id: light.basement_escalier_switch
      state: 'off'
  action:
    - service: light.turn_on
      data:
        entity_id:
          - light.basement_escalier_switch
