# thermostats
- alias: 'Cal thermostats'
  initial_state: false
  trigger:
    - platform: state
      entity_id:
        - calendar.thermostat_bedroom
        - calendar.thermostat_living
  action:
    - service: system_log.write
      data_template:
        level: info
        message: |
          to_state = {{ trigger.to_state.state }}
          entity_id = {{ trigger.entity_id }}
          device_name = {{ state_attr(trigger.entity_id, 'message') }}
          description = {{ state_attr(trigger.entity_id, 'description') }}
    - service: script.climate_set
      data_template:
        state: >-
          {% if trigger.to_state.state == 'on' %}
            on
          {% else %}
            {% set evtStr = state_attr(trigger.entity_id, 'description') %}
            {% if evtStr is not none and evtStr != "" %}
              {% set evt = evtStr | string | lower | from_json %}
              {{ 'eco' if 'eco' in evt else 'off' }}
            {% else %}
              off
            {% endif %}
          {% endif %}
        entity_id: >-
          {% set str = state_attr(trigger.entity_id, 'message') %}
          {% if str is not none and str | string | lower | regex_search("#([a-z0-9]+)") %}
            {% set device_name = str | string | lower | regex_findall_index("#([a-z0-9]+)") %}
            climate.{{ device_name }}
          {% else %}
            climate.unknown
          {% endif %}
        temperature: >-
          {% set evtStr = state_attr(trigger.entity_id, 'description') %}
          {% if evtStr is not none and evtStr != "" %}
            {% set evt = evtStr | string | lower | from_json %}
            {{ evt.temperature | float(default=18) }}
          {% else %}
            {{ "18" | float }}
          {% endif %}
        temperature_eco: >-
          {% set evtStr = state_attr(trigger.entity_id, 'description') %}
          {% if evtStr is not none and evtStr != "" %}
            {% set evt = evtStr | string | lower | from_json %}
            {% if 'eco' in evt %}
              {{ evt.eco | float }}
            {% else %}
              16
            {% endif %}
          {% else %}
            16
          {% endif %}
