# Migrated to node red
- alias: 'Estrade dehumidifier ON'
  initial_state: 'false'
  trigger:
  - platform: numeric_state
    entity_id: sensor.estrade_am2301_humidity
    above: '52'
    below: '100'
    for: 00:00:10
  condition:
  - condition: time
    after: '10:00:01'
    before: '21:30:00'
  action:
  - service: switch.turn_on
    data:
      entity_id: switch.estrade_relay

- alias: 'Estrade dehumidifier morning ON'
  initial_state: 'false'
  trigger:
  - platform: time
    at: '10:00:00'
  condition: []
  action:
  - service: switch.turn_on
    data:
     entity_id: switch.estrade_relay

- alias: 'Estrade dehumidifier OFF if below'
  initial_state: 'false'
  trigger:
  - platform: numeric_state
    above: '5'
    below: '40'
    entity_id: sensor.estrade_am2301_humidity
    for: 00:00:10
  condition: []
  action:
  - service: switch.turn_off
    data:
      entity_id: switch.estrade_relay
