- alias: 'Estrade dehumidifier ON'
  trigger:
  - platform: numeric_state
    entity_id: sensor.estrade_am2301_humidity
    above: '52'
    below: '100'
    for: 00:00:10
  condition:
  - condition: time
    after: '10:00:00'
    before: '21:59:59'
  action:
  - service: switch.turn_on
    data:
      entity_id: switch.estrade_relay

- alias: 'Estrade dehumidifier OFF'
  trigger:
  - platform: time
    at: '22:00:00'
  condition: []
  action:
  - service: switch.turn_off
    data:
     entity_id: switch.estrade_relay
  # reset above automation state in case switch is turned off
  # whereas humidity is already > threshold%
  # In this case, it will never be triggered again (because already triggered
  # during the day and switch is now off, so humidity will continuously rise
  # and never gets under threshold again...)
  - service: script.reset_dehumidifier_on_automation


- alias: 'Estrade dehumidifier OFF if below'
  trigger:
  - platform: numeric_state
    above: '5'
    below: '39'
    entity_id: sensor.estrade_am2301_humidity
    for: 00:00:10
  condition: []
  action:
  - service: switch.turn_off
    data:
      entity_id: switch.estrade_relay
