- alias: 'Entree auto off'
  trigger:
    - platform: state
      from: 'off'
      to: 'on'
      entity_id: light.entree_switch
      for: 00:03:00
  action:
    - service: light.turn_off
      data:
        entity_id:
          - light.entree_switch
