- alias: Heating ON bedroom (evening)
  trigger:
    - platform: time
      at: '22:00'
  condition: []
  action:
    - service: climate.turn_on
      entity_id: climate.bedroom
    - service: climate.set_temperature
      entity_id: climate.bedroom
      data:
        temperature: 19.5

- alias: Heating ECO bedroom (night)
  trigger:
    - platform: time
      at: '02:00'
  condition: []
  action:
    - service: climate.turn_on
      entity_id: climate.bedroom
    - service: climate.set_temperature
      entity_id: climate.bedroom
      data:
        temperature: 18

- alias: Heating ON bedroom (morning)
  trigger:
    - platform: time
      at: '08:10'
  condition: []
  action:
    - service: climate.turn_on
      entity_id: climate.bedroom
    - service: climate.set_temperature
      entity_id: climate.bedroom
      data:
        temperature: 19.5

- alias: Heating OFF bedroom (day)
  trigger:
    - platform: time
      at: '09:50'
  condition: []
  action:
    - service: climate.turn_off
      entity_id: climate.bedroom
